version: "3.9"

services:
  mongo-shopping:
    image: mongo:6
    container_name: mongo-shopping
    ports:
      - "27017:27017"
    volumes:
      - mongo_shopping_data:/data/db
    networks:
      - app-network

  mongo-payment:
    image: mongo:6
    container_name: mongo-payment
    ports:
      - "27018:27017"
    volumes:
      - mongo_payment_data:/data/db
    networks:
      - app-network

  mongo-auth:
    image: mongo:6
    container_name: mongo-auth
    ports:
      - "27019:27017"
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - app-network

  shopping-service:
    build:
      context: ./shopping-service
    container_name: shopping-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo-shopping
    environment:
      PORT: "8080"
      MONGOURI: "mongodb://mongo-shopping:27017"
      MONGODB_NAME: "shopping_db"
      PAYMENT_SERVICE_URL: "http://payment-service:8081"
    networks:
      - app-network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "50051:50051"
    depends_on:
      - mongo-payment
    environment:
      PORT: "8081"
      GRPC_PORT: "50051"
      MONGOURI: "mongodb://mongo-payment:27017"
      MONGODB_NAME: "payment_db"
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "50052:50052"
    depends_on:
      - mongo-auth
    environment:
      PORT: "50052"
      AUTH_MONGO_URI: "mongodb://mongo-auth:27017"
      AUTH_DB_NAME: "auth_db"
      AUTH_JWT_SECRET: "mysecretkey123"
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8082:8082"
    depends_on:
      - shopping-service
      - payment-service
      - auth-service
    environment:
      GATEWAY_PORT: ":8082"
      AUTH_SERVICE_ADDR: "auth-service:50052"
      SHOPPING_SERVICE_URL: "http://shopping-service:8080"
      PAYMENT_SERVICE_GRPC_ADDR: "payment-service:50051"
      PAYMENT_SERVICE_REST_URL: "http://payment-service:8081"
      JWT_SECRET: "mysecretkey123"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_shopping_data:
  mongo_payment_data:
  mongo_auth_data:
