version: "3.9"

services:
  shopping-service:
    build:
      context: ./shopping-service
    container_name: shopping-service
    ports:
      - "8080:8080"
    env_file:
      - ./shopping-service/.env
    networks:
      - app-network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "50051:50051"
    env_file:
      - ./payment-service/.env
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "50052:50052"
    env_file:
      - ./auth-service/.env
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8082:8082"
    env_file:
      - ./gateway-service/.env
    depends_on:
      - shopping-service
      - payment-service
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
