// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protoc/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data payment yang akan dipakai sebagai response
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_protoc_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Digunakan saat membuat payment
type AddPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPaymentRequest) Reset() {
	*x = AddPaymentRequest{}
	mi := &file_protoc_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentRequest) ProtoMessage() {}

func (x *AddPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentRequest.ProtoReflect.Descriptor instead.
func (*AddPaymentRequest) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{1}
}

func (x *AddPaymentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AddPaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Digunakan untuk ambil/hapus payment by ID
type GetPaymentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIDRequest) Reset() {
	*x = GetPaymentByIDRequest{}
	mi := &file_protoc_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIDRequest) ProtoMessage() {}

func (x *GetPaymentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByIDRequest) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePaymentByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentByIDRequest) Reset() {
	*x = DeletePaymentByIDRequest{}
	mi := &file_protoc_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentByIDRequest) ProtoMessage() {}

func (x *DeletePaymentByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentByIDRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentByIDRequest) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePaymentByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Digunakan untuk ambil semua data
type GetAllPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPaymentsRequest) Reset() {
	*x = GetAllPaymentsRequest{}
	mi := &file_protoc_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPaymentsRequest) ProtoMessage() {}

func (x *GetAllPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{4}
}

type GetAllPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPaymentsResponse) Reset() {
	*x = GetAllPaymentsResponse{}
	mi := &file_protoc_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPaymentsResponse) ProtoMessage() {}

func (x *GetAllPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_protoc_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

var File_protoc_payment_proto protoreflect.FileDescriptor

const file_protoc_payment_proto_rawDesc = "" +
	"\n" +
	"\x14protoc/payment.proto\x12\apayment\"_\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"Y\n" +
	"\x11AddPaymentRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"'\n" +
	"\x15GetPaymentByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18DeletePaymentByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15GetAllPaymentsRequest\"F\n" +
	"\x16GetAllPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments2\xad\x02\n" +
	"\x0ePaymentService\x12:\n" +
	"\n" +
	"AddPayment\x12\x1a.payment.AddPaymentRequest\x1a\x10.payment.Payment\x12B\n" +
	"\x0eGetPaymentByID\x12\x1e.payment.GetPaymentByIDRequest\x1a\x10.payment.Payment\x12H\n" +
	"\x11DeletePaymentByID\x12!.payment.DeletePaymentByIDRequest\x1a\x10.payment.Payment\x12Q\n" +
	"\x0eGetAllPayments\x12\x1e.payment.GetAllPaymentsRequest\x1a\x1f.payment.GetAllPaymentsResponseB*Z(internal/payment/delivery/grpc/paymentpbb\x06proto3"

var (
	file_protoc_payment_proto_rawDescOnce sync.Once
	file_protoc_payment_proto_rawDescData []byte
)

func file_protoc_payment_proto_rawDescGZIP() []byte {
	file_protoc_payment_proto_rawDescOnce.Do(func() {
		file_protoc_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protoc_payment_proto_rawDesc), len(file_protoc_payment_proto_rawDesc)))
	})
	return file_protoc_payment_proto_rawDescData
}

var file_protoc_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protoc_payment_proto_goTypes = []any{
	(*Payment)(nil),                  // 0: payment.Payment
	(*AddPaymentRequest)(nil),        // 1: payment.AddPaymentRequest
	(*GetPaymentByIDRequest)(nil),    // 2: payment.GetPaymentByIDRequest
	(*DeletePaymentByIDRequest)(nil), // 3: payment.DeletePaymentByIDRequest
	(*GetAllPaymentsRequest)(nil),    // 4: payment.GetAllPaymentsRequest
	(*GetAllPaymentsResponse)(nil),   // 5: payment.GetAllPaymentsResponse
}
var file_protoc_payment_proto_depIdxs = []int32{
	0, // 0: payment.GetAllPaymentsResponse.payments:type_name -> payment.Payment
	1, // 1: payment.PaymentService.AddPayment:input_type -> payment.AddPaymentRequest
	2, // 2: payment.PaymentService.GetPaymentByID:input_type -> payment.GetPaymentByIDRequest
	3, // 3: payment.PaymentService.DeletePaymentByID:input_type -> payment.DeletePaymentByIDRequest
	4, // 4: payment.PaymentService.GetAllPayments:input_type -> payment.GetAllPaymentsRequest
	0, // 5: payment.PaymentService.AddPayment:output_type -> payment.Payment
	0, // 6: payment.PaymentService.GetPaymentByID:output_type -> payment.Payment
	0, // 7: payment.PaymentService.DeletePaymentByID:output_type -> payment.Payment
	5, // 8: payment.PaymentService.GetAllPayments:output_type -> payment.GetAllPaymentsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_payment_proto_init() }
func file_protoc_payment_proto_init() {
	if File_protoc_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protoc_payment_proto_rawDesc), len(file_protoc_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_payment_proto_goTypes,
		DependencyIndexes: file_protoc_payment_proto_depIdxs,
		MessageInfos:      file_protoc_payment_proto_msgTypes,
	}.Build()
	File_protoc_payment_proto = out.File
	file_protoc_payment_proto_goTypes = nil
	file_protoc_payment_proto_depIdxs = nil
}
